import type { SupportedLocale } from "@/lib/vonu-check/types";
import type { IndexedPublicSlug } from "@/lib/vonu-global/i18n";

export const INTENT_SLUGS = [
  "comprobar-web-fiable",
  "comprobar-tienda-online",
  "analizar-link-sospechoso",
  "analizar-captura-pantalla",
  "analizar-sms-estafa",
  "email-sospechoso-estafa",
  "detectar-perfil-falso",
  "comprobar-inversion-estafa",
  "revisar-contrato",
  "revisar-contrato-alquiler",
  "comprobar-factura",
  "revisar-presupuesto",
  "revisar-contrato-servicios",
  "revisar-prestamo-financiacion",
  "detectar-manipulacion",
  "estafas-criptomonedas",
  "llamada-banco-codigo-sms",
  "es-fiable",
] as const;

export type IntentSlug = (typeof INTENT_SLUGS)[number];
type IntentGroup = "web" | "link" | "capture" | "message" | "identity" | "investment" | "documents" | "manipulation" | "generic";

type GroupCopy = {
  signalsTitle: string;
  stepsTitle: string;
  signals: string[];
  steps: string[];
  faqs: Array<{ q: string; a: string }>;
};

export const intentLabels: Record<SupportedLocale, {
  answer: string;
  faq: string;
  related: string;
  cautionTitle: string;
  caution: string;
  cta: string;
}> = {
  es: {
    answer: "Respuesta rápida",
    faq: "Preguntas concretas",
    related: "También puede ayudarte",
    cautionTitle: "Qué puede y qué no puede decirte Vonu",
    caution: "Vonu organiza señales observables y contexto para ayudarte a comprobar mejor una situación. No certifica que una persona, web, mensaje o documento sea legítimo o fraudulento y no sustituye a autoridades ni profesionales.",
    cta: "Analizar ahora",
  },
  en: {
    answer: "Quick answer",
    faq: "Specific questions",
    related: "You may also need",
    cautionTitle: "What Vonu can and cannot tell you",
    caution: "Vonu organises observable signals and context to help you verify a situation more carefully. It does not certify that a person, website, message or document is legitimate or fraudulent, and it does not replace authorities or professionals.",
    cta: "Analyse now",
  },
  fr: {
    answer: "Réponse rapide",
    faq: "Questions concrètes",
    related: "Cela peut aussi vous aider",
    cautionTitle: "Ce que Vonu peut et ne peut pas conclure",
    caution: "Vonu organise les signaux observables et le contexte pour vous aider à mieux vérifier une situation. Il ne certifie pas qu’une personne, un site, un message ou un document est légitime ou frauduleux et ne remplace pas les autorités ni les professionnels.",
    cta: "Analyser maintenant",
  },
  de: {
    answer: "Kurzantwort",
    faq: "Konkrete Fragen",
    related: "Das könnte ebenfalls helfen",
    cautionTitle: "Was Vonu sagen kann – und was nicht",
    caution: "Vonu ordnet beobachtbare Signale und Kontext, damit du eine Situation sorgfältiger prüfen kannst. Es bestätigt nicht, dass eine Person, Website, Nachricht oder ein Dokument seriös oder betrügerisch ist, und ersetzt keine Behörden oder Fachleute.",
    cta: "Jetzt analysieren",
  },
  ar: {
    answer: "إجابة سريعة",
    faq: "أسئلة محددة",
    related: "قد تحتاج أيضًا إلى",
    cautionTitle: "ما الذي يستطيع Vonu قوله وما الذي لا يستطيع",
    caution: "ينظم Vonu الإشارات القابلة للملاحظة والسياق لمساعدتك على التحقق من الموقف بعناية أكبر. لا يؤكد أن شخصًا أو موقعًا أو رسالة أو مستندًا شرعي أو احتيالي، ولا يحل محل الجهات الرسمية أو المختصين.",
    cta: "حلّل الآن",
  },
};

const groupBySlug: Record<IntentSlug, IntentGroup> = {
  "comprobar-web-fiable": "web",
  "comprobar-tienda-online": "web",
  "analizar-link-sospechoso": "link",
  "analizar-captura-pantalla": "capture",
  "analizar-sms-estafa": "message",
  "email-sospechoso-estafa": "message",
  "detectar-perfil-falso": "identity",
  "comprobar-inversion-estafa": "investment",
  "revisar-contrato": "documents",
  "revisar-contrato-alquiler": "documents",
  "comprobar-factura": "documents",
  "revisar-presupuesto": "documents",
  "revisar-contrato-servicios": "documents",
  "revisar-prestamo-financiacion": "documents",
  "detectar-manipulacion": "manipulation",
  "estafas-criptomonedas": "investment",
  "llamada-banco-codigo-sms": "message",
  "es-fiable": "generic",
};

const answers: Record<SupportedLocale, Record<IntentSlug, string>> = {
  es: {
    "comprobar-web-fiable": "Una web no es fiable solo porque tenga HTTPS o un diseño profesional. Comprueba quién está detrás, la antigüedad y coherencia del dominio, los métodos de contacto, las condiciones de compra y cualquier señal técnica o comercial que no encaje antes de pagar o compartir datos.",
    "comprobar-tienda-online": "Antes de comprar en una tienda desconocida, contrasta identidad, dominio, precios, métodos de pago, políticas de devolución y reputación externa. Un descuento extraordinario o una urgencia artificial no demuestran una estafa, pero sí justifican verificar más.",
    "analizar-link-sospechoso": "No abras un enlace dudoso para comprobarlo. Revisa el dominio real, acortadores, redirecciones, errores de suplantación y el contexto del mensaje que lo contiene. Si pide iniciar sesión, pagar o introducir códigos, usa primero el canal oficial de la entidad.",
    "analizar-captura-pantalla": "Una captura puede revelar presión, suplantación, datos de pago, dominios, nombres de usuario y otras señales útiles. Vonu puede ordenar esas pistas, pero una imagen aislada puede omitir contexto importante y no prueba por sí sola que exista fraude.",
    "analizar-sms-estafa": "Desconfía especialmente de SMS o WhatsApp que combinan urgencia con enlaces, pagos, códigos o amenazas. No respondas ni pulses el enlace hasta verificar el aviso mediante la app, web o teléfono oficial de la entidad.",
    "email-sospechoso-estafa": "En un correo sospechoso importa más el dominio real del remitente, los enlaces y lo que te pide hacer que el logotipo que muestra. Verifica por un canal independiente antes de iniciar sesión, descargar archivos o pagar.",
    "detectar-perfil-falso": "Un perfil falso suele descubrirse por incoherencias acumuladas, no por una sola señal: antigüedad, historial, fotos, red de contactos, cambios de identidad y peticiones de dinero o datos. Verifica la identidad fuera de la propia cuenta.",
    "comprobar-inversion-estafa": "Ninguna rentabilidad prometida sustituye la verificación. Comprueba la entidad, regulación aplicable, custodia del dinero, condiciones de retirada, presión comercial y si puedes confirmar la oferta en fuentes independientes antes de transferir fondos.",
    "revisar-contrato": "Antes de firmar, identifica quiénes son las partes, qué obligaciones asume cada una, duración, pagos, penalizaciones, causas de resolución y jurisdicción. Las cláusulas ambiguas o desequilibradas merecen una revisión profesional cuando el impacto sea importante.",
    "revisar-contrato-alquiler": "En un alquiler conviene revisar identidad del arrendador, inmueble, renta, actualización, fianza, duración, desistimiento, suministros, reparaciones y penalizaciones. Si una cláusula no se entiende, no la des por válida solo porque aparezca en el contrato.",
    "comprobar-factura": "Comprueba emisor, concepto, fechas, impuestos, cuenta de pago y coherencia con el pedido o servicio original. Si ha cambiado el IBAN o la factura llega con urgencia inesperada, confirma el cambio por un canal conocido antes de pagar.",
    "revisar-presupuesto": "Antes de aceptar un presupuesto o proforma, revisa proveedor, alcance, opciones, impuestos, vigencia, anticipos, condiciones de pago, exclusiones y garantías. Un precio claro no basta si faltan condiciones que pueden cambiar el coste final.",
    "revisar-contrato-servicios": "En un contrato de servicios conviene revisar qué se entrega, cuánto cuesta, cuánto dura, cómo se renueva o cancela, qué responsabilidades asume cada parte y qué ocurre si el servicio no cumple lo esperado.",
    "revisar-prestamo-financiacion": "Antes de aceptar financiación, revisa principal, intereses, cuotas, comisiones, coste total, vencimiento anticipado, garantías y consecuencias del impago. Si la jurisdicción o alguna condición no está clara, pide aclaración antes de firmar.",
    "detectar-manipulacion": "La manipulación no se demuestra con una frase aislada. Busca patrones repetidos de presión, culpa, aislamiento, amenazas, cambios de versión o exigencias de actuar sin tiempo para pensar y conserva el contexto completo antes de sacar conclusiones.",
    "estafas-criptomonedas": "En cripto, una transferencia puede ser irreversible. Verifica plataforma, dominio, wallet, promesas de rentabilidad, supuestos soportes, recuperación de fondos y cualquier petición de enviar más dinero para desbloquear retiradas antes de firmar o transferir.",
    "llamada-banco-codigo-sms": "Si alguien que dice ser tu banco te pide un código SMS, PIN, contraseña o que muevas dinero con urgencia, corta la comunicación y llama tú al número oficial. El nombre que aparece en una llamada o SMS puede falsificarse.",
    "es-fiable": "La fiabilidad se evalúa reuniendo varias señales: identidad, dominio, contexto, forma de pago, presión, coherencia y verificación externa. Una sola señal positiva —como HTTPS, seguidores o un logotipo— no basta para dar algo por seguro.",
  },
  en: {
    "comprobar-web-fiable": "A website is not trustworthy simply because it uses HTTPS or looks professional. Check who is behind it, domain age and consistency, contact methods, purchase terms, and technical or commercial warning signs before paying or sharing data.",
    "comprobar-tienda-online": "Before buying from an unfamiliar store, verify identity, domain, pricing, payment methods, return policies and independent reputation. An extraordinary discount or artificial urgency does not prove a scam, but it is a reason to verify more carefully.",
    "analizar-link-sospechoso": "Do not open a doubtful link just to inspect it. Check the real domain, shorteners, redirects, impersonation tricks and the context of the message. If it asks you to log in, pay or enter codes, use the organisation’s official channel first.",
    "analizar-captura-pantalla": "A screenshot can reveal pressure, impersonation, payment details, domains, usernames and other useful signals. Vonu can organise those clues, but a single image may omit important context and cannot by itself prove fraud.",
    "analizar-sms-estafa": "Be especially cautious with SMS or WhatsApp messages that combine urgency with links, payments, codes or threats. Do not reply or tap the link until you verify the alert through the organisation’s official app, website or phone number.",
    "email-sospechoso-estafa": "For a suspicious email, the real sender domain, destination links and requested action matter more than the logo it displays. Verify through an independent channel before signing in, downloading files or paying.",
    "detectar-perfil-falso": "Fake profiles are usually identified through accumulated inconsistencies rather than one clue: account age, history, photos, contact network, identity changes and requests for money or data. Verify the person outside the account itself.",
    "comprobar-inversion-estafa": "A promised return is never a substitute for verification. Check the entity, applicable regulation, custody of funds, withdrawal terms, sales pressure and whether the offer can be confirmed through independent sources before transferring money.",
    "revisar-contrato": "Before signing, identify the parties, each side’s obligations, duration, payments, penalties, termination rights and jurisdiction. Ambiguous or one-sided clauses deserve professional review when the consequences are significant.",
    "revisar-contrato-alquiler": "For a rental agreement, check the landlord’s identity, property, rent, increases, deposit, duration, termination, utilities, repairs and penalties. If a clause is unclear, do not assume it is valid merely because it appears in the contract.",
    "comprobar-factura": "Check the issuer, description, dates, taxes, payment account and consistency with the original order or service. If the bank account has changed or the invoice arrives with unusual urgency, confirm the change through a known channel before paying.",
    "revisar-presupuesto": "Before accepting a quote or pro forma, review the supplier, scope, options, taxes, validity, deposits, payment terms, exclusions and guarantees. A clear price is not enough if missing conditions could change the final cost.",
    "revisar-contrato-servicios": "For a service contract, review what will be delivered, price, duration, renewal or termination, each party’s responsibilities and what happens if the service falls short of what was agreed.",
    "revisar-prestamo-financiacion": "Before accepting financing, review principal, interest, instalments, fees, total cost, acceleration terms, guarantees and late-payment consequences. If jurisdiction or an important condition is unclear, seek clarification before signing.",
    "detectar-manipulacion": "Manipulation cannot be established from one isolated sentence. Look for repeated patterns of pressure, guilt, isolation, threats, shifting stories or demands to act without time to think, and keep the wider context before drawing conclusions.",
    "estafas-criptomonedas": "Crypto transfers can be irreversible. Verify the platform, domain, wallet, return promises, supposed support agents, recovery offers and any request to send more money to unlock withdrawals before signing or transferring.",
    "llamada-banco-codigo-sms": "If someone claiming to be your bank asks for an SMS code, PIN, password or an urgent transfer, end the call and contact the bank yourself using its official number. Caller ID and SMS sender names can be spoofed.",
    "es-fiable": "Trustworthiness is assessed by combining signals: identity, domain, context, payment method, pressure, consistency and independent verification. One positive clue — such as HTTPS, followers or a logo — is not enough to make something safe.",
  },
  fr: {
    "comprobar-web-fiable": "Un site n’est pas fiable simplement parce qu’il utilise HTTPS ou paraît professionnel. Vérifiez l’identité de l’opérateur, l’ancienneté et la cohérence du domaine, les contacts, les conditions d’achat et les signaux techniques ou commerciaux avant de payer ou partager des données.",
    "comprobar-tienda-online": "Avant d’acheter sur une boutique inconnue, vérifiez l’identité, le domaine, les prix, les moyens de paiement, les retours et la réputation externe. Une remise exceptionnelle ou une urgence artificielle ne prouve pas une arnaque, mais justifie davantage de vérifications.",
    "analizar-link-sospechoso": "N’ouvrez pas un lien douteux uniquement pour le tester. Vérifiez le domaine réel, les raccourcisseurs, les redirections, les techniques d’usurpation et le contexte du message. S’il demande une connexion, un paiement ou un code, utilisez d’abord le canal officiel.",
    "analizar-captura-pantalla": "Une capture peut révéler pression, usurpation, données de paiement, domaines, noms d’utilisateur et autres indices. Vonu peut organiser ces éléments, mais une image isolée peut manquer de contexte et ne prouve pas à elle seule une fraude.",
    "analizar-sms-estafa": "Soyez particulièrement prudent avec les SMS ou WhatsApp qui combinent urgence, liens, paiement, codes ou menaces. Ne répondez pas et ne cliquez pas avant d’avoir vérifié l’alerte dans l’application, le site ou le numéro officiel de l’organisation.",
    "email-sospechoso-estafa": "Dans un email suspect, le vrai domaine de l’expéditeur, les liens et l’action demandée comptent davantage que le logo affiché. Vérifiez par un canal indépendant avant de vous connecter, télécharger un fichier ou payer.",
    "detectar-perfil-falso": "Un faux profil se repère souvent par l’accumulation d’incohérences : ancienneté, historique, photos, réseau, changements d’identité et demandes d’argent ou de données. Vérifiez l’identité en dehors du compte lui-même.",
    "comprobar-inversion-estafa": "Une promesse de rendement ne remplace jamais une vérification. Contrôlez l’entité, la réglementation, la garde des fonds, les retraits, la pression commerciale et la possibilité de confirmer l’offre auprès de sources indépendantes avant tout virement.",
    "revisar-contrato": "Avant de signer, identifiez les parties, leurs obligations, la durée, les paiements, pénalités, motifs de résiliation et la juridiction. Les clauses ambiguës ou déséquilibrées méritent un avis professionnel lorsque l’enjeu est important.",
    "revisar-contrato-alquiler": "Pour un bail, vérifiez l’identité du bailleur, le logement, le loyer, sa révision, le dépôt, la durée, le départ, les charges, réparations et pénalités. Une clause incomprise ne devient pas valable simplement parce qu’elle figure dans le contrat.",
    "comprobar-factura": "Vérifiez l’émetteur, l’objet, les dates, taxes, compte de paiement et cohérence avec la commande ou le service. Si l’IBAN change ou si l’urgence est inhabituelle, confirmez le changement par un canal connu avant de payer.",
    "revisar-presupuesto": "Avant d’accepter un devis ou une pro forma, vérifiez fournisseur, périmètre, options, taxes, validité, acomptes, modalités de paiement, exclusions et garanties. Un prix clair ne suffit pas si des conditions peuvent modifier le coût final.",
    "revisar-contrato-servicios": "Dans un contrat de services, vérifiez les livrables, le prix, la durée, le renouvellement ou la résiliation, les responsabilités de chaque partie et les conséquences si le service n’est pas conforme aux attentes.",
    "revisar-prestamo-financiacion": "Avant d’accepter un financement, vérifiez capital, intérêts, échéances, frais, coût total, exigibilité anticipée, garanties et conséquences d’un retard. Si la juridiction ou une condition importante est floue, demandez des précisions avant de signer.",
    "detectar-manipulacion": "La manipulation ne se démontre pas avec une phrase isolée. Recherchez des schémas répétés de pression, culpabilisation, isolement, menaces, versions changeantes ou exigences d’agir sans réfléchir et conservez le contexte complet.",
    "estafas-criptomonedas": "Les transferts crypto peuvent être irréversibles. Vérifiez la plateforme, le domaine, le wallet, les promesses de rendement, les faux supports, les offres de récupération et toute demande d’envoyer davantage d’argent pour débloquer un retrait.",
    "llamada-banco-codigo-sms": "Si une personne se présentant comme votre banque demande un code SMS, PIN, mot de passe ou virement urgent, raccrochez et appelez vous-même le numéro officiel. Le nom affiché lors d’un appel ou d’un SMS peut être usurpé.",
    "es-fiable": "La fiabilité s’évalue en combinant plusieurs signaux : identité, domaine, contexte, paiement, pression, cohérence et vérification externe. Un seul indice positif — HTTPS, abonnés ou logo — ne suffit pas pour conclure qu’une situation est sûre.",
  },
  de: {
    "comprobar-web-fiable": "Eine Website ist nicht allein deshalb seriös, weil sie HTTPS nutzt oder professionell aussieht. Prüfe Betreiber, Alter und Konsistenz der Domain, Kontaktwege, Kaufbedingungen sowie technische und geschäftliche Warnsignale, bevor du zahlst oder Daten teilst.",
    "comprobar-tienda-online": "Bevor du bei einem unbekannten Shop kaufst, prüfe Identität, Domain, Preise, Zahlungsarten, Rückgaberegeln und externe Reputation. Ein außergewöhnlicher Rabatt oder künstliche Dringlichkeit beweist keinen Betrug, ist aber ein Grund für zusätzliche Prüfung.",
    "analizar-link-sospechoso": "Öffne einen zweifelhaften Link nicht nur, um ihn zu testen. Prüfe echte Domain, Kurz-URLs, Weiterleitungen, Nachahmungen und den Nachrichtenkontext. Wenn Login, Zahlung oder Codes verlangt werden, nutze zuerst den offiziellen Kanal der Organisation.",
    "analizar-captura-pantalla": "Ein Screenshot kann Druck, Identitätsvortäuschung, Zahlungsdaten, Domains, Nutzernamen und andere Hinweise zeigen. Vonu kann diese Signale ordnen, aber ein einzelnes Bild kann wichtigen Kontext auslassen und beweist allein keinen Betrug.",
    "analizar-sms-estafa": "Sei besonders vorsichtig bei SMS oder WhatsApp-Nachrichten, die Dringlichkeit mit Links, Zahlungen, Codes oder Drohungen verbinden. Antworte nicht und öffne keinen Link, bevor du die Meldung über App, Website oder offizielle Telefonnummer geprüft hast.",
    "email-sospechoso-estafa": "Bei einer verdächtigen E-Mail sind die echte Absenderdomain, Ziel-Links und geforderte Handlung wichtiger als das angezeigte Logo. Prüfe über einen unabhängigen Kanal, bevor du dich anmeldest, Dateien lädst oder zahlst.",
    "detectar-perfil-falso": "Fake-Profile erkennt man meist an mehreren Unstimmigkeiten: Kontoalter, Verlauf, Fotos, Kontaktnetz, Identitätswechsel und Geld- oder Datenforderungen. Prüfe die Identität außerhalb des Profils.",
    "comprobar-inversion-estafa": "Eine Renditeversprechung ersetzt keine Prüfung. Kontrolliere Anbieter, Regulierung, Verwahrung der Gelder, Auszahlungsbedingungen, Verkaufsdruck und ob sich das Angebot unabhängig bestätigen lässt, bevor du Geld überweist.",
    "revisar-contrato": "Vor der Unterschrift solltest du Parteien, Pflichten, Laufzeit, Zahlungen, Vertragsstrafen, Kündigungsrechte und Gerichtsstand erkennen. Unklare oder einseitige Klauseln sollten bei erheblichen Folgen professionell geprüft werden.",
    "revisar-contrato-alquiler": "Bei einem Mietvertrag prüfe Vermieteridentität, Objekt, Miete, Erhöhungen, Kaution, Laufzeit, Kündigung, Nebenkosten, Reparaturen und Sanktionen. Eine unklare Klausel ist nicht automatisch wirksam, nur weil sie im Vertrag steht.",
    "comprobar-factura": "Prüfe Aussteller, Leistung, Daten, Steuern, Zahlungskonto und Übereinstimmung mit Bestellung oder Dienstleistung. Wenn sich die IBAN geändert hat oder ungewöhnlicher Zeitdruck besteht, bestätige die Änderung über einen bekannten Kanal.",
    "revisar-presupuesto": "Prüfe vor der Annahme eines Angebots oder einer Proforma Anbieter, Leistungsumfang, Optionen, Steuern, Gültigkeit, Anzahlungen, Zahlungsbedingungen, Ausschlüsse und Garantien. Ein klarer Preis reicht nicht, wenn Bedingungen den Endpreis verändern können.",
    "revisar-contrato-servicios": "Bei einem Dienstleistungsvertrag solltest du Leistungsumfang, Vergütung, Laufzeit, Verlängerung oder Kündigung, Pflichten beider Parteien und Folgen bei mangelhafter Leistung prüfen.",
    "revisar-prestamo-financiacion": "Prüfe vor einer Finanzierung Kapital, Zinsen, Raten, Gebühren, Gesamtkosten, vorzeitige Fälligkeit, Sicherheiten und Folgen bei Zahlungsverzug. Ist die Rechtsordnung oder eine wichtige Bedingung unklar, kläre sie vor der Unterschrift.",
    "detectar-manipulacion": "Manipulation lässt sich nicht aus einem einzelnen Satz ableiten. Achte auf wiederholte Muster von Druck, Schuldzuweisung, Isolation, Drohungen, wechselnden Darstellungen oder Forderungen ohne Bedenkzeit und berücksichtige den gesamten Kontext.",
    "estafas-criptomonedas": "Krypto-Transfers können unumkehrbar sein. Prüfe Plattform, Domain, Wallet, Renditeversprechen, angebliche Support-Mitarbeiter, Rückholangebote und jede Forderung nach weiterem Geld, um Auszahlungen freizuschalten.",
    "llamada-banco-codigo-sms": "Wenn jemand angeblich von deiner Bank einen SMS-Code, PIN, ein Passwort oder eine dringende Überweisung verlangt, beende den Kontakt und rufe selbst die offizielle Nummer an. Rufnummern und SMS-Absendernamen können gefälscht werden.",
    "es-fiable": "Seriosität beurteilt man durch mehrere Signale: Identität, Domain, Kontext, Zahlungsart, Druck, Konsistenz und unabhängige Bestätigung. Ein positives Merkmal wie HTTPS, Follower oder ein Logo reicht nicht aus.",
  },
  ar: {
    "comprobar-web-fiable": "لا يصبح الموقع موثوقًا لمجرد استخدام HTTPS أو امتلاكه تصميمًا احترافيًا. تحقّق من الجهة التي تقف خلفه، وعمر النطاق واتساقه، ووسائل الاتصال، وشروط الشراء، وأي إشارات تقنية أو تجارية غير منطقية قبل الدفع أو مشاركة البيانات.",
    "comprobar-tienda-online": "قبل الشراء من متجر غير معروف، تحقّق من الهوية والنطاق والأسعار وطرق الدفع وسياسة الإرجاع والسمعة في مصادر مستقلة. الخصم الاستثنائي أو الاستعجال المصطنع لا يثبت الاحتيال، لكنه سبب كافٍ لمزيد من التحقق.",
    "analizar-link-sospechoso": "لا تفتح رابطًا مشبوهًا فقط لاختباره. افحص النطاق الحقيقي والروابط المختصرة وإعادة التوجيه وأساليب الانتحال وسياق الرسالة. إذا طُلب منك تسجيل الدخول أو الدفع أو إدخال رمز، استخدم القناة الرسمية للجهة أولًا.",
    "analizar-captura-pantalla": "قد تكشف لقطة الشاشة ضغطًا أو انتحالًا أو بيانات دفع أو نطاقات أو أسماء مستخدمين وإشارات أخرى مفيدة. يستطيع Vonu تنظيم هذه القرائن، لكن الصورة المنفردة قد تفتقد سياقًا مهمًا ولا تثبت الاحتيال بمفردها.",
    "analizar-sms-estafa": "كن حذرًا خصوصًا من رسائل SMS أو WhatsApp التي تجمع بين الاستعجال وروابط أو مدفوعات أو رموز أو تهديدات. لا ترد ولا تضغط الرابط حتى تتحقق من التنبيه عبر التطبيق أو الموقع أو الرقم الرسمي للجهة.",
    "email-sospechoso-estafa": "في البريد المشبوه، النطاق الحقيقي للمرسل والروابط والإجراء المطلوب أهم من الشعار الظاهر. تحقّق عبر قناة مستقلة قبل تسجيل الدخول أو تنزيل الملفات أو الدفع.",
    "detectar-perfil-falso": "غالبًا ما يُكتشف الحساب المزيف من تراكم التناقضات لا من إشارة واحدة: عمر الحساب، تاريخه، الصور، شبكة العلاقات، تغيّر الهوية وطلبات المال أو البيانات. تحقّق من الهوية خارج الحساب نفسه.",
    "comprobar-inversion-estafa": "الوعد بالعائد لا يغني عن التحقق. افحص الجهة والتنظيم المطبق وحفظ الأموال وشروط السحب والضغط التسويقي وإمكانية تأكيد العرض من مصادر مستقلة قبل تحويل المال.",
    "revisar-contrato": "قبل التوقيع، حدّد الأطراف والتزامات كل طرف والمدة والمدفوعات والغرامات وحقوق الإنهاء والاختصاص القضائي. البنود الغامضة أو غير المتوازنة تستحق مراجعة مختص عندما تكون العواقب كبيرة.",
    "revisar-contrato-alquiler": "في عقد الإيجار، راجع هوية المؤجر والعقار والإيجار وزياداته والتأمين والمدة والإنهاء والمرافق والإصلاحات والغرامات. لا تفترض أن البند صحيح لمجرد وجوده في العقد إذا لم يكن واضحًا.",
    "comprobar-factura": "تحقّق من الجهة المصدرة والوصف والتواريخ والضرائب وحساب الدفع واتساقها مع الطلب أو الخدمة الأصلية. إذا تغيّر رقم الحساب أو ظهرت عجلة غير معتادة، أكّد التغيير عبر قناة معروفة قبل الدفع.",
    "revisar-presupuesto": "قبل قبول عرض سعر أو فاتورة مبدئية، راجع المورّد والنطاق والخيارات والضرائب ومدة الصلاحية والدفعات وشروط الدفع والاستثناءات والضمانات. السعر الواضح وحده لا يكفي إذا كانت هناك شروط قد تغيّر التكلفة النهائية.",
    "revisar-contrato-servicios": "في عقد الخدمات، راجع ما سيتم تقديمه والسعر والمدة والتجديد أو الإنهاء ومسؤوليات كل طرف وما يحدث إذا لم تُقدَّم الخدمة كما هو متفق.",
    "revisar-prestamo-financiacion": "قبل قبول التمويل، راجع أصل المبلغ والفوائد والأقساط والرسوم والتكلفة الإجمالية والاستحقاق المبكر والضمانات وعواقب التأخر في السداد. إذا كانت الولاية القضائية أو أي شرط مهم غير واضح، فاطلب توضيحًا قبل التوقيع.",
    "detectar-manipulacion": "لا يمكن إثبات التلاعب من جملة منفردة. ابحث عن أنماط متكررة من الضغط أو الإحساس بالذنب أو العزل أو التهديد أو تغيّر الرواية أو المطالبة بالتصرف دون وقت للتفكير، واحتفظ بالسياق الكامل.",
    "estafas-criptomonedas": "قد تكون تحويلات العملات المشفرة غير قابلة للعكس. تحقّق من المنصة والنطاق والمحفظة ووعود العائد والدعم المزعوم وخدمات استرداد الأموال وأي طلب لإرسال مال إضافي لفتح السحب قبل التحويل.",
    "llamada-banco-codigo-sms": "إذا طلب شخص يدّعي أنه من البنك رمز SMS أو PIN أو كلمة مرور أو تحويلًا عاجلًا، أنهِ الاتصال واتصل أنت بالرقم الرسمي للبنك. يمكن تزوير اسم المتصل أو مرسل الرسالة.",
    "es-fiable": "تُقيّم الموثوقية بجمع عدة إشارات: الهوية والنطاق والسياق وطريقة الدفع والضغط والاتساق والتحقق المستقل. إشارة إيجابية واحدة مثل HTTPS أو عدد المتابعين أو الشعار لا تكفي للحكم بالأمان.",
  },
};

const groupCopy: Record<SupportedLocale, Record<IntentGroup, GroupCopy>> = {
  es: {
    web: { signalsTitle: "Señales que conviene contrastar", stepsTitle: "Qué hacer antes de comprar o confiar", signals: ["Identidad empresarial, contacto y coherencia de los datos legales.", "Dominio, antigüedad, redirecciones y parecido con marcas conocidas.", "Precios, métodos de pago, devoluciones y presión para actuar rápido.", "Reputación externa y consistencia entre lo que promete la web y lo verificable fuera de ella."], steps: ["Busca la empresa y el dominio por separado, no solo desde enlaces de la propia web.", "Si vas a pagar, prioriza métodos con protección y evita transferencias irreversibles ante dudas.", "Si algo no encaja, analiza la URL y conserva capturas antes de continuar."], faqs: [{ q: "¿Tener HTTPS significa que la web es segura?", a: "No. HTTPS cifra la conexión, pero una web fraudulenta también puede usar un certificado válido." }, { q: "¿Un dominio nuevo demuestra una estafa?", a: "No por sí solo. Es una señal contextual que debe combinarse con identidad, reputación, contenido y comportamiento comercial." }, { q: "¿Qué hago si ya he pagado?", a: "Guarda pruebas, contacta cuanto antes con tu banco o proveedor de pago y utiliza los canales oficiales de denuncia o soporte cuando corresponda." }] },
    link: { signalsTitle: "Qué mirar en un enlace", stepsTitle: "Cómo comprobarlo sin exponerte", signals: ["El dominio registrable real, no solo el texto visible del enlace.", "Subdominios, caracteres parecidos, acortadores y parámetros que ocultan el destino.", "Cadenas de redirección y cambios de dominio antes de llegar a la página final.", "El contexto: quién lo envía, qué pide y si intenta provocar urgencia o miedo."], steps: ["No introduzcas credenciales ni códigos desde el enlace recibido.", "Abre por separado la app o web oficial de la entidad y comprueba allí la supuesta alerta.", "Analiza la URL como texto antes de visitarla si aún tienes dudas."], faqs: [{ q: "¿Puedo fiarme si el enlace empieza por https://?", a: "No. HTTPS protege la conexión, no garantiza la legitimidad del sitio de destino." }, { q: "¿Los enlaces cortos son peligrosos?", a: "No necesariamente, pero ocultan el destino y por eso requieren más precaución cuando llegan en mensajes inesperados." }, { q: "¿Qué pasa si ya lo abrí?", a: "Abrirlo no implica automáticamente un compromiso. Evita introducir datos, cierra la página y cambia credenciales si llegaste a entregarlas." }] },
    capture: { signalsTitle: "Qué puede revelar una captura", stepsTitle: "Cómo aportar contexto útil", signals: ["Dominio, remitente, nombre de usuario o identidad mostrada.", "Peticiones de dinero, códigos, credenciales o datos personales.", "Lenguaje de urgencia, amenaza, premio o presión emocional.", "Errores visuales, incoherencias y elementos que imitan a una entidad conocida."], steps: ["Incluye, si puedes, la parte de la captura donde aparezcan remitente, URL o contexto.", "Oculta contraseñas, PIN, números completos de tarjeta y códigos de autenticación.", "Contrasta cualquier conclusión con el canal oficial de la persona o entidad implicada."], faqs: [{ q: "¿Una captura basta para demostrar una estafa?", a: "No. Puede aportar señales muy útiles, pero también puede estar incompleta, editada o carecer de contexto." }, { q: "¿Debo subir datos sensibles?", a: "No. Oculta contraseñas, códigos, PIN y datos completos de tarjetas antes de analizar una imagen." }, { q: "¿Vonu puede detectar una imagen manipulada?", a: "Puede señalar incoherencias visibles, pero no certifica autenticidad forense de una imagen." }] },
    message: { signalsTitle: "Señales habituales en mensajes de riesgo", stepsTitle: "Qué hacer antes de responder", signals: ["Urgencia artificial: plazos mínimos, bloqueos, multas o amenazas inmediatas.", "Petición de códigos, contraseñas, datos bancarios o transferencias.", "Enlaces cuyo dominio no coincide con la entidad que dice escribirte.", "Remitente o teléfono que parece legítimo pero no puede verificarse por un canal independiente."], steps: ["No respondas ni compartas códigos de autenticación.", "Entra manualmente en la app o web oficial o llama a un número que ya conozcas.", "Guarda el mensaje y analiza texto, enlaces o captura antes de tomar una decisión."], faqs: [{ q: "¿El nombre del remitente demuestra quién lo envía?", a: "No. En SMS, correo y llamadas existen técnicas para falsificar o imitar nombres y direcciones visibles." }, { q: "¿Mi banco puede pedirme un código SMS?", a: "Un código de autenticación es extremadamente sensible. No lo compartas con alguien que te lo solicite por llamada o mensaje; verifica directamente con tu banco." }, { q: "¿Debo contestar para comprobar si es real?", a: "No es necesario. Es más seguro verificar por un canal oficial independiente." }] },
    identity: { signalsTitle: "Qué comprobar en un perfil", stepsTitle: "Cómo verificar la identidad", signals: ["Antigüedad, cambios de nombre, historial y coherencia temporal del perfil.", "Fotos, biografía y datos que también puedan verificarse fuera de esa cuenta.", "Red de contactos, interacciones reales y patrones de seguidores poco naturales.", "Peticiones de dinero, inversión, datos personales o traslado rápido a otro canal."], steps: ["Busca la identidad por otras fuentes y compara fotos, nombres y actividad.", "Pide una verificación razonable por un canal distinto si la relación lo justifica.", "No envíes dinero ni documentación sensible basándote únicamente en el perfil."], faqs: [{ q: "¿Pocas publicaciones significan que sea falso?", a: "No. Es una señal débil por sí sola; importa el conjunto de coherencia, historial e identidad verificable." }, { q: "¿Una videollamada prueba la identidad?", a: "Aporta contexto, pero tampoco es una garantía absoluta. La verificación debe ser proporcional al riesgo de la acción que vayas a realizar." }, { q: "¿Qué hago si están suplantando a alguien?", a: "Conserva pruebas, avisa a la persona real por otro canal y utiliza las herramientas de denuncia de la plataforma." }] },
    investment: { signalsTitle: "Señales que requieren especial cautela", stepsTitle: "Qué verificar antes de enviar dinero", signals: ["Rentabilidad garantizada, beneficios desproporcionados o ausencia de explicación del riesgo.", "Presión para ingresar rápido, aumentar posición o no retirar fondos.", "Entidades, licencias o profesionales que no pueden verificarse en registros independientes.", "Pagos en cripto, wallets, cuentas de terceros o nuevas comisiones para liberar retiradas."], steps: ["Verifica la empresa y la regulación en la fuente oficial correspondiente.", "Comprueba quién custodia el dinero y cómo funciona realmente la retirada antes de ingresar.", "No envíes más fondos para recuperar una inversión sin verificar independientemente la situación."], faqs: [{ q: "¿Una plataforma con beneficios visibles es legítima?", a: "No necesariamente. Un saldo mostrado en pantalla no demuestra que el dinero exista ni que pueda retirarse." }, { q: "¿Pagar una tasa para desbloquear la retirada es normal?", a: "Puede ser una señal de alto riesgo, especialmente si aparecen nuevas tasas cada vez que intentas retirar. Verifica la entidad antes de pagar más." }, { q: "¿Qué hago si ya envié dinero o cripto?", a: "Conserva direcciones, hashes, recibos y conversaciones y contacta cuanto antes con tu proveedor, banco o autoridades competentes según el caso." }] },
    documents: { signalsTitle: "Puntos que conviene localizar", stepsTitle: "Cómo revisar antes de aceptar o pagar", signals: ["Identidad de las partes, objeto del documento y datos que deberían coincidir con la relación real.", "Importes, fechas, duración, renovaciones, penalizaciones y condiciones de salida.", "Cuentas bancarias, datos de pago o cambios respecto a documentos anteriores.", "Cláusulas ambiguas, contradictorias o que trasladan un riesgo desproporcionado a una sola parte."], steps: ["Compara el documento con la oferta, conversación o contrato previo que lo originó.", "Marca cualquier dato que no puedas verificar y pide aclaración por escrito.", "Si la consecuencia económica o jurídica es relevante, utiliza una revisión profesional antes de firmar o pagar."], faqs: [{ q: "¿Vonu puede decir si una cláusula es legal?", a: "No sustituye asesoramiento jurídico. Puede ayudarte a localizar y ordenar cláusulas para que sepas qué conviene revisar o preguntar." }, { q: "¿Un cambio de cuenta bancaria es una señal de fraude?", a: "No siempre, pero debe confirmarse por un canal conocido antes de realizar un pago." }, { q: "¿Qué datos debería ocultar al analizar un documento?", a: "Evita compartir contraseñas, códigos de autenticación, números completos de tarjeta y cualquier dato extremadamente sensible que no sea necesario para la revisión." }] },
    manipulation: { signalsTitle: "Patrones que merece la pena observar", stepsTitle: "Cómo recuperar margen para decidir", signals: ["Presión repetida para responder, pagar o decidir sin tiempo suficiente.", "Culpa, amenazas, castigo emocional o aislamiento de otras fuentes de opinión.", "Cambios constantes de versión o negación de hechos fácilmente comprobables.", "Alternancia de premio y presión para conseguir una conducta concreta."], steps: ["Separa hechos verificables de interpretaciones y conserva el contexto completo.", "Evita decisiones importantes mientras exista presión inmediata y consulta a una persona de confianza cuando sea apropiado.", "Si existe amenaza, coacción o riesgo personal, prioriza apoyo profesional o de las autoridades."], faqs: [{ q: "¿Una discusión fuerte significa manipulación?", a: "No. Hace falta contexto y un patrón; una interacción aislada no permite una conclusión fiable." }, { q: "¿Vonu puede diagnosticar a una persona?", a: "No. Vonu puede ordenar conductas observables, no diagnosticar personalidad, salud mental ni intenciones internas." }, { q: "¿Qué información es más útil?", a: "Una secuencia completa de mensajes o hechos, fechas y contexto suele ser más útil que una frase aislada." }] },
    generic: { signalsTitle: "Las señales que más pesan", stepsTitle: "Una comprobación sencilla antes de actuar", signals: ["Identidad: quién está realmente detrás y si puede verificarse fuera del propio canal.", "Coherencia: dominio, historia, datos, precios y comportamiento encajan entre sí.", "Riesgo de la acción: dinero, códigos, credenciales, documentos o información sensible.", "Presión: urgencia, amenazas o incentivos para impedir que compruebes por otra vía."], steps: ["Detén la acción si el coste de equivocarte es alto y falta información.", "Verifica por al menos una fuente independiente o canal oficial.", "Analiza URL, mensaje o captura y decide después con las señales ordenadas."], faqs: [{ q: "¿Una sola señal permite saber si es fiable?", a: "Normalmente no. La confianza mejora al combinar varias señales independientes y valorar también lo que no puede verificarse." }, { q: "¿Vonu da un veredicto definitivo?", a: "No. Presenta señales, evidencia disponible e incertidumbre para ayudarte a decidir qué verificar después." }, { q: "¿Qué debería comprobar primero?", a: "La identidad y la acción que te están pidiendo: quién es, cómo puedes confirmarlo y qué perderías si la solicitud fuese falsa." }] },
  },
  en: {
    web: { signalsTitle: "Signals worth cross-checking", stepsTitle: "What to do before buying or trusting", signals: ["Business identity, contact details and consistency of legal information.", "Domain, age, redirects and resemblance to known brands.", "Pricing, payment methods, returns and pressure to act quickly.", "Independent reputation and consistency between what the site claims and what can be verified elsewhere."], steps: ["Search for the company and domain independently rather than relying on links from the site itself.", "If you pay, prefer methods with buyer protection and avoid irreversible transfers while doubts remain.", "If something feels inconsistent, analyse the URL and save screenshots before continuing."], faqs: [{ q: "Does HTTPS mean a website is safe?", a: "No. HTTPS encrypts the connection, but a fraudulent website can also use a valid certificate." }, { q: "Does a new domain prove a scam?", a: "Not by itself. It is contextual evidence that should be combined with identity, reputation, content and commercial behaviour." }, { q: "What if I already paid?", a: "Save evidence, contact your bank or payment provider quickly, and use official reporting or support channels where appropriate." }] },
    link: { signalsTitle: "What to inspect in a link", stepsTitle: "How to check it without exposing yourself", signals: ["The real registrable domain, not just the visible link text.", "Subdomains, look-alike characters, shorteners and parameters that hide the destination.", "Redirect chains and domain changes before the final page.", "Context: who sent it, what it asks you to do and whether it creates urgency or fear."], steps: ["Do not enter credentials or authentication codes from a received link.", "Open the organisation’s official app or website separately and check the claimed alert there.", "Analyse the URL as text before visiting it if you still have doubts."], faqs: [{ q: "Can I trust a link because it starts with https://?", a: "No. HTTPS protects the connection; it does not guarantee that the destination is legitimate." }, { q: "Are shortened links dangerous?", a: "Not necessarily, but they hide the destination, so they deserve extra caution in unexpected messages." }, { q: "What if I already opened it?", a: "Opening a page does not automatically mean compromise. Avoid entering data, close it, and change credentials if you submitted them." }] },
    capture: { signalsTitle: "What a screenshot can reveal", stepsTitle: "How to provide useful context", signals: ["Domain, sender, username or displayed identity.", "Requests for money, codes, credentials or personal data.", "Language of urgency, threat, reward or emotional pressure.", "Visual inconsistencies and elements imitating a known organisation."], steps: ["If possible, include the part showing the sender, URL or surrounding context.", "Hide passwords, PINs, full card numbers and authentication codes.", "Cross-check any conclusion through the official channel of the person or organisation involved."], faqs: [{ q: "Is a screenshot enough to prove a scam?", a: "No. It can provide valuable signals, but it may be incomplete, edited or missing important context." }, { q: "Should I upload sensitive data?", a: "No. Hide passwords, codes, PINs and full card details before analysing an image." }, { q: "Can Vonu detect an edited image?", a: "It can flag visible inconsistencies, but it does not certify the forensic authenticity of an image." }] },
    message: { signalsTitle: "Common warning signs in risky messages", stepsTitle: "What to do before replying", signals: ["Artificial urgency: short deadlines, blocks, fines or immediate threats.", "Requests for codes, passwords, banking details or transfers.", "Links whose domains do not match the organisation claiming to contact you.", "A sender or phone number that looks legitimate but cannot be confirmed independently."], steps: ["Do not reply with authentication codes or sensitive credentials.", "Open the official app or website manually, or call a number you already know.", "Save the message and analyse its text, links or screenshot before making a decision."], faqs: [{ q: "Does the sender name prove who sent it?", a: "No. SMS, email and phone systems can be spoofed or made to imitate legitimate names and addresses." }, { q: "Can my bank ask for an SMS code?", a: "Authentication codes are extremely sensitive. Do not give one to someone asking by phone or message; verify directly with your bank." }, { q: "Should I reply to see whether it is real?", a: "You do not need to. It is safer to verify through an independent official channel." }] },
    identity: { signalsTitle: "What to check in a profile", stepsTitle: "How to verify identity", signals: ["Account age, name changes, history and timeline consistency.", "Photos, biography and details that can also be verified outside the account.", "Contact network, genuine interactions and unnatural follower patterns.", "Requests for money, investments, personal data or a rapid move to another channel."], steps: ["Search the identity through other sources and compare photos, names and activity.", "Use reasonable verification through a different channel when the relationship and risk justify it.", "Do not send money or sensitive documents based solely on the profile."], faqs: [{ q: "Do few posts mean the profile is fake?", a: "No. It is a weak signal on its own; the broader consistency, history and verifiable identity matter more." }, { q: "Does a video call prove identity?", a: "It adds context but is not an absolute guarantee. Verification should match the risk of the action you are considering." }, { q: "What if someone is impersonating a real person?", a: "Save evidence, warn the real person through another channel and use the platform’s reporting tools." }] },
    investment: { signalsTitle: "Signals that require extra caution", stepsTitle: "What to verify before sending money", signals: ["Guaranteed returns, disproportionate profits or no meaningful explanation of risk.", "Pressure to deposit quickly, increase a position or avoid withdrawing.", "Entities, licences or professionals that cannot be verified in independent registers.", "Crypto payments, third-party accounts or new fees required to release withdrawals."], steps: ["Verify the company and regulatory status at the relevant official source.", "Understand who holds the money and how withdrawal actually works before depositing.", "Do not send more funds to recover an investment until the situation has been independently verified."], faqs: [{ q: "Does an on-screen profit balance prove the platform is legitimate?", a: "No. A displayed balance does not prove that the money exists or can be withdrawn." }, { q: "Is it normal to pay a fee to unlock a withdrawal?", a: "It can be a high-risk signal, especially if new fees appear each time you try to withdraw. Verify the entity before paying more." }, { q: "What if I already sent money or crypto?", a: "Keep addresses, transaction hashes, receipts and conversations, and contact your provider, bank or relevant authorities as quickly as appropriate." }] },
    documents: { signalsTitle: "Points worth locating", stepsTitle: "How to review before accepting or paying", signals: ["Identity of the parties, purpose of the document and details that should match the real relationship.", "Amounts, dates, duration, renewals, penalties and exit conditions.", "Bank accounts, payment details or changes from previous documents.", "Ambiguous, contradictory or unusually one-sided clauses."], steps: ["Compare the document with the offer, conversation or previous agreement that produced it.", "Mark anything you cannot verify and request clarification in writing.", "If the legal or financial consequence is significant, seek professional review before signing or paying."], faqs: [{ q: "Can Vonu tell me whether a clause is legal?", a: "It does not replace legal advice. It can help locate and organise clauses so you know what to review or ask about." }, { q: "Does a changed bank account mean fraud?", a: "Not always, but it should be confirmed through a known channel before payment." }, { q: "What data should I hide before analysing a document?", a: "Avoid sharing passwords, authentication codes, full card numbers and extremely sensitive data that is not necessary for the review." }] },
    manipulation: { signalsTitle: "Patterns worth observing", stepsTitle: "How to regain room to decide", signals: ["Repeated pressure to answer, pay or decide without enough time.", "Guilt, threats, emotional punishment or isolation from other opinions.", "Constantly shifting stories or denial of easily verifiable facts.", "Alternating reward and pressure to obtain a specific behaviour."], steps: ["Separate verifiable facts from interpretations and keep the wider context.", "Avoid major decisions under immediate pressure and consult a trusted person when appropriate.", "If there is threat, coercion or personal danger, prioritise professional or official support."], faqs: [{ q: "Does a heated argument mean manipulation?", a: "No. Context and pattern matter; one isolated interaction is not enough for a reliable conclusion." }, { q: "Can Vonu diagnose a person?", a: "No. Vonu can organise observable behaviour, not diagnose personality, mental health or internal motives." }, { q: "What information is most useful?", a: "A complete sequence of messages or events, dates and context is usually more useful than one isolated sentence." }] },
    generic: { signalsTitle: "The signals that matter most", stepsTitle: "A simple check before acting", signals: ["Identity: who is really behind it and whether that can be verified elsewhere.", "Consistency: whether domain, history, details, pricing and behaviour fit together.", "Risk of the requested action: money, codes, credentials, documents or sensitive information.", "Pressure: urgency, threats or incentives designed to prevent independent verification."], steps: ["Pause if the cost of being wrong is high and information is missing.", "Verify through at least one independent source or official channel.", "Analyse the URL, message or screenshot and decide once the signals are organised."], faqs: [{ q: "Can one signal tell me whether something is trustworthy?", a: "Usually not. Confidence improves when several independent signals agree and uncertainty is also considered." }, { q: "Does Vonu give a final verdict?", a: "No. It presents signals, available evidence and uncertainty to help you decide what to verify next." }, { q: "What should I check first?", a: "The identity and the requested action: who is asking, how you can confirm them and what you could lose if the request were false." }] },
  },
  fr: {
    web: { signalsTitle: "Signaux à recouper", stepsTitle: "Que faire avant d’acheter ou de faire confiance", signals: ["Identité de l’entreprise, contacts et cohérence des informations légales.", "Domaine, ancienneté, redirections et ressemblance avec des marques connues.", "Prix, moyens de paiement, retours et pression pour agir vite.", "Réputation externe et cohérence entre les promesses du site et ce qui peut être vérifié ailleurs."], steps: ["Recherchez séparément l’entreprise et le domaine au lieu de vous fier aux liens du site.", "Pour payer, privilégiez les moyens offrant une protection et évitez les virements irréversibles en cas de doute.", "Si quelque chose ne colle pas, analysez l’URL et conservez des captures avant de continuer."], faqs: [{ q: "HTTPS signifie-t-il qu’un site est sûr ?", a: "Non. HTTPS chiffre la connexion, mais un site frauduleux peut également avoir un certificat valide." }, { q: "Un domaine récent prouve-t-il une arnaque ?", a: "Non. C’est un élément de contexte à combiner avec l’identité, la réputation, le contenu et le comportement commercial." }, { q: "Que faire si j’ai déjà payé ?", a: "Conservez les preuves, contactez rapidement votre banque ou moyen de paiement et utilisez les canaux officiels de signalement si nécessaire." }] },
    link: { signalsTitle: "Ce qu’il faut vérifier dans un lien", stepsTitle: "Comment le contrôler sans s’exposer", signals: ["Le vrai domaine enregistrable, pas seulement le texte affiché.", "Sous-domaines, caractères ressemblants, raccourcisseurs et paramètres qui cachent la destination.", "Chaînes de redirection et changements de domaine avant la page finale.", "Le contexte : qui l’envoie, ce qui est demandé et la présence d’urgence ou de peur."], steps: ["N’entrez pas d’identifiants ni de codes depuis un lien reçu.", "Ouvrez séparément l’application ou le site officiel de l’organisation et vérifiez l’alerte annoncée.", "Analysez l’URL comme texte avant de la visiter si le doute persiste."], faqs: [{ q: "Puis-je faire confiance à un lien parce qu’il commence par https:// ?", a: "Non. HTTPS protège la connexion, pas la légitimité de la destination." }, { q: "Les liens raccourcis sont-ils dangereux ?", a: "Pas nécessairement, mais ils masquent la destination et exigent donc plus de prudence dans un message inattendu." }, { q: "Et si j’ai déjà ouvert le lien ?", a: "L’ouverture seule ne signifie pas automatiquement une compromission. N’entrez pas de données et changez vos identifiants si vous les avez fournis." }] },
    capture: { signalsTitle: "Ce qu’une capture peut révéler", stepsTitle: "Comment fournir un contexte utile", signals: ["Domaine, expéditeur, nom d’utilisateur ou identité affichée.", "Demandes d’argent, de codes, d’identifiants ou de données personnelles.", "Langage d’urgence, menace, récompense ou pression émotionnelle.", "Incohérences visuelles et éléments imitant une organisation connue."], steps: ["Incluez si possible la zone montrant l’expéditeur, l’URL ou le contexte.", "Masquez mots de passe, PIN, numéros complets de carte et codes d’authentification.", "Recoupez toute conclusion avec le canal officiel de la personne ou de l’organisation concernée."], faqs: [{ q: "Une capture suffit-elle à prouver une arnaque ?", a: "Non. Elle peut apporter des signaux utiles mais être incomplète, modifiée ou manquer de contexte." }, { q: "Dois-je envoyer des données sensibles ?", a: "Non. Masquez mots de passe, codes, PIN et données complètes de carte avant l’analyse." }, { q: "Vonu peut-il détecter une image modifiée ?", a: "Il peut signaler des incohérences visibles, mais ne certifie pas l’authenticité forensique d’une image." }] },
    message: { signalsTitle: "Signaux fréquents dans les messages à risque", stepsTitle: "Que faire avant de répondre", signals: ["Urgence artificielle : délais courts, blocages, amendes ou menaces immédiates.", "Demandes de codes, mots de passe, données bancaires ou virements.", "Liens dont le domaine ne correspond pas à l’organisation prétendue.", "Expéditeur ou numéro apparemment légitime mais impossible à confirmer indépendamment."], steps: ["Ne répondez pas avec des codes d’authentification ou des identifiants sensibles.", "Ouvrez manuellement l’application ou le site officiel, ou appelez un numéro déjà connu.", "Conservez le message et analysez son texte, ses liens ou sa capture avant de décider."], faqs: [{ q: "Le nom de l’expéditeur prouve-t-il son identité ?", a: "Non. Les SMS, emails et appels peuvent être usurpés ou imiter des noms et adresses légitimes." }, { q: "Ma banque peut-elle demander un code SMS ?", a: "Les codes d’authentification sont extrêmement sensibles. Ne les communiquez pas à une personne qui les demande par appel ou message; vérifiez directement avec votre banque." }, { q: "Dois-je répondre pour voir si c’est vrai ?", a: "Ce n’est pas nécessaire. Il est plus sûr de vérifier via un canal officiel indépendant." }] },
    identity: { signalsTitle: "Ce qu’il faut vérifier sur un profil", stepsTitle: "Comment vérifier l’identité", signals: ["Ancienneté du compte, changements de nom, historique et cohérence temporelle.", "Photos, biographie et informations vérifiables en dehors du compte.", "Réseau de contacts, interactions réelles et schémas de followers peu naturels.", "Demandes d’argent, d’investissement, de données ou déplacement rapide vers un autre canal."], steps: ["Recherchez l’identité dans d’autres sources et comparez photos, noms et activité.", "Utilisez une vérification raisonnable par un autre canal lorsque le risque le justifie.", "N’envoyez ni argent ni document sensible sur la seule base du profil."], faqs: [{ q: "Peu de publications signifie-t-il que le profil est faux ?", a: "Non. C’est un indice faible isolément; la cohérence globale, l’historique et l’identité vérifiable comptent davantage." }, { q: "Un appel vidéo prouve-t-il l’identité ?", a: "Il apporte du contexte mais n’est pas une garantie absolue. La vérification doit être proportionnelle au risque de l’action envisagée." }, { q: "Que faire en cas d’usurpation ?", a: "Conservez les preuves, prévenez la personne réelle par un autre canal et utilisez les outils de signalement de la plateforme." }] },
    investment: { signalsTitle: "Signaux exigeant une prudence renforcée", stepsTitle: "Que vérifier avant d’envoyer de l’argent", signals: ["Rendements garantis, profits disproportionnés ou absence d’explication réelle du risque.", "Pression pour déposer vite, augmenter une position ou ne pas retirer.", "Entités, licences ou professionnels introuvables dans des registres indépendants.", "Paiements en crypto, comptes tiers ou nouvelles commissions exigées pour libérer un retrait."], steps: ["Vérifiez l’entreprise et son statut réglementaire auprès de la source officielle compétente.", "Comprenez qui conserve les fonds et comment fonctionne réellement le retrait avant de déposer.", "N’envoyez pas davantage d’argent pour récupérer un investissement sans vérification indépendante."], faqs: [{ q: "Un solde bénéficiaire affiché prouve-t-il la légitimité de la plateforme ?", a: "Non. Un solde à l’écran ne prouve ni l’existence des fonds ni leur possibilité de retrait." }, { q: "Est-il normal de payer pour débloquer un retrait ?", a: "Cela peut être un signal de risque élevé, surtout si de nouveaux frais apparaissent à chaque tentative. Vérifiez l’entité avant de payer davantage." }, { q: "Que faire si j’ai déjà envoyé de l’argent ou des cryptos ?", a: "Conservez adresses, hashes, reçus et conversations et contactez rapidement votre prestataire, banque ou autorités compétentes selon le cas." }] },
    documents: { signalsTitle: "Points à repérer", stepsTitle: "Comment vérifier avant d’accepter ou de payer", signals: ["Identité des parties, objet du document et données devant correspondre à la relation réelle.", "Montants, dates, durée, renouvellements, pénalités et conditions de sortie.", "Comptes bancaires, données de paiement ou changements par rapport aux documents précédents.", "Clauses ambiguës, contradictoires ou anormalement déséquilibrées."], steps: ["Comparez le document avec l’offre, la conversation ou l’accord précédent dont il découle.", "Marquez tout élément invérifiable et demandez une clarification écrite.", "Si l’enjeu juridique ou financier est important, faites relire par un professionnel avant de signer ou payer."], faqs: [{ q: "Vonu peut-il dire si une clause est légale ?", a: "Il ne remplace pas un conseil juridique. Il peut aider à repérer et organiser les clauses afin de savoir quoi vérifier ou demander." }, { q: "Un changement de compte bancaire signifie-t-il une fraude ?", a: "Pas toujours, mais il doit être confirmé par un canal connu avant tout paiement." }, { q: "Quelles données masquer avant d’analyser un document ?", a: "Évitez mots de passe, codes d’authentification, numéros complets de carte et données extrêmement sensibles inutiles à la vérification." }] },
    manipulation: { signalsTitle: "Schémas à observer", stepsTitle: "Comment retrouver une marge de décision", signals: ["Pression répétée pour répondre, payer ou décider sans temps suffisant.", "Culpabilisation, menaces, sanction émotionnelle ou isolement des autres avis.", "Versions qui changent constamment ou négation de faits facilement vérifiables.", "Alternance de récompense et de pression pour obtenir un comportement précis."], steps: ["Séparez les faits vérifiables des interprétations et conservez le contexte global.", "Évitez les décisions importantes sous pression immédiate et consultez une personne de confiance si approprié.", "En cas de menace, contrainte ou danger personnel, privilégiez un soutien professionnel ou officiel."], faqs: [{ q: "Une dispute intense signifie-t-elle manipulation ?", a: "Non. Le contexte et la répétition comptent; une interaction isolée ne suffit pas à une conclusion fiable." }, { q: "Vonu peut-il diagnostiquer une personne ?", a: "Non. Vonu peut organiser des comportements observables, pas diagnostiquer une personnalité, une santé mentale ou des intentions internes." }, { q: "Quelles informations sont les plus utiles ?", a: "Une séquence complète de messages ou faits, avec dates et contexte, est généralement plus utile qu’une phrase isolée." }] },
    generic: { signalsTitle: "Les signaux qui comptent le plus", stepsTitle: "Une vérification simple avant d’agir", signals: ["Identité : qui est réellement derrière et si cela peut être vérifié ailleurs.", "Cohérence : domaine, historique, données, prix et comportement concordent-ils ?", "Risque de l’action demandée : argent, codes, identifiants, documents ou données sensibles.", "Pression : urgence, menaces ou incitations destinées à empêcher une vérification indépendante."], steps: ["Arrêtez-vous si le coût d’une erreur est élevé et qu’il manque des informations.", "Vérifiez au moins une source indépendante ou un canal officiel.", "Analysez l’URL, le message ou la capture puis décidez une fois les signaux organisés."], faqs: [{ q: "Un seul signal permet-il de savoir si c’est fiable ?", a: "En général non. La confiance augmente lorsque plusieurs signaux indépendants concordent et que l’incertitude est prise en compte." }, { q: "Vonu donne-t-il un verdict définitif ?", a: "Non. Il présente les signaux, les éléments disponibles et l’incertitude pour aider à choisir la prochaine vérification." }, { q: "Que vérifier en premier ?", a: "L’identité et l’action demandée : qui vous sollicite, comment le confirmer et ce que vous pourriez perdre si la demande était fausse." }] },
  },
  de: {
    web: { signalsTitle: "Signale, die du gegenprüfen solltest", stepsTitle: "Was du vor Kauf oder Vertrauen tun solltest", signals: ["Unternehmensidentität, Kontaktmöglichkeiten und Konsistenz rechtlicher Angaben.", "Domain, Alter, Weiterleitungen und Ähnlichkeit mit bekannten Marken.", "Preise, Zahlungsarten, Rückgaben und Druck, schnell zu handeln.", "Externe Reputation und Übereinstimmung zwischen Behauptungen der Website und unabhängig prüfbaren Fakten."], steps: ["Suche Unternehmen und Domain unabhängig und nicht nur über Links der Website.", "Nutze beim Bezahlen möglichst Verfahren mit Käuferschutz und vermeide irreversible Überweisungen bei Zweifel.", "Wenn etwas nicht passt, analysiere die URL und sichere Screenshots, bevor du fortfährst."], faqs: [{ q: "Bedeutet HTTPS, dass eine Website sicher ist?", a: "Nein. HTTPS verschlüsselt die Verbindung, aber auch eine betrügerische Website kann ein gültiges Zertifikat verwenden." }, { q: "Beweist eine neue Domain Betrug?", a: "Nein. Sie ist nur ein Kontextsignal und sollte mit Identität, Reputation, Inhalt und Geschäftsverhalten kombiniert werden." }, { q: "Was, wenn ich schon bezahlt habe?", a: "Sichere Belege, kontaktiere Bank oder Zahlungsanbieter schnell und nutze gegebenenfalls offizielle Melde- oder Supportwege." }] },
    link: { signalsTitle: "Was du bei einem Link prüfen solltest", stepsTitle: "So prüfst du ihn ohne unnötiges Risiko", signals: ["Die echte registrierbare Domain, nicht nur den sichtbaren Linktext.", "Subdomains, ähnlich aussehende Zeichen, Kurz-URLs und Parameter, die das Ziel verbergen.", "Weiterleitungsketten und Domainwechsel vor der Zielseite.", "Den Kontext: Wer hat ihn geschickt, was wird verlangt und wird Dringlichkeit oder Angst erzeugt?"], steps: ["Gib keine Zugangsdaten oder Authentifizierungscodes über einen empfangenen Link ein.", "Öffne die offizielle App oder Website separat und prüfe die behauptete Meldung dort.", "Analysiere die URL als Text, bevor du sie besuchst, wenn Zweifel bleiben."], faqs: [{ q: "Ist ein Link vertrauenswürdig, wenn er mit https:// beginnt?", a: "Nein. HTTPS schützt die Verbindung, garantiert aber nicht die Legitimität des Ziels." }, { q: "Sind Kurzlinks gefährlich?", a: "Nicht grundsätzlich, aber sie verbergen das Ziel und erfordern bei unerwarteten Nachrichten zusätzliche Vorsicht." }, { q: "Was, wenn ich ihn bereits geöffnet habe?", a: "Das Öffnen allein bedeutet nicht automatisch eine Kompromittierung. Gib keine Daten ein und ändere Zugangsdaten, falls du sie übermittelt hast." }] },
    capture: { signalsTitle: "Was ein Screenshot zeigen kann", stepsTitle: "So lieferst du nützlichen Kontext", signals: ["Domain, Absender, Nutzername oder angezeigte Identität.", "Forderungen nach Geld, Codes, Zugangsdaten oder persönlichen Daten.", "Sprache mit Dringlichkeit, Drohung, Belohnung oder emotionalem Druck.", "Visuelle Unstimmigkeiten und Elemente, die bekannte Organisationen imitieren."], steps: ["Zeige möglichst den Bereich mit Absender, URL oder relevantem Kontext.", "Blende Passwörter, PINs, vollständige Kartennummern und Authentifizierungscodes aus.", "Bestätige Schlussfolgerungen über den offiziellen Kanal der betroffenen Person oder Organisation."], faqs: [{ q: "Reicht ein Screenshot als Beweis für Betrug?", a: "Nein. Er kann wertvolle Signale liefern, aber unvollständig, bearbeitet oder ohne wichtigen Kontext sein." }, { q: "Sollte ich sensible Daten hochladen?", a: "Nein. Blende Passwörter, Codes, PINs und vollständige Kartendaten aus." }, { q: "Kann Vonu eine manipulierte Grafik erkennen?", a: "Es kann sichtbare Unstimmigkeiten markieren, bestätigt aber keine forensische Echtheit eines Bildes." }] },
    message: { signalsTitle: "Häufige Warnsignale in riskanten Nachrichten", stepsTitle: "Was du vor einer Antwort tun solltest", signals: ["Künstliche Dringlichkeit: kurze Fristen, Sperren, Geldstrafen oder unmittelbare Drohungen.", "Forderungen nach Codes, Passwörtern, Bankdaten oder Überweisungen.", "Links, deren Domain nicht zur angeblichen Organisation passt.", "Absender oder Telefonnummer wirken legitim, lassen sich aber nicht unabhängig bestätigen."], steps: ["Antworte nicht mit Authentifizierungscodes oder sensiblen Zugangsdaten.", "Öffne App oder Website manuell oder rufe eine bereits bekannte offizielle Nummer an.", "Sichere die Nachricht und analysiere Text, Links oder Screenshot, bevor du entscheidest."], faqs: [{ q: "Beweist der Absendername, wer die Nachricht geschickt hat?", a: "Nein. SMS, E-Mail und Telefon können so manipuliert werden, dass legitime Namen oder Adressen angezeigt werden." }, { q: "Kann meine Bank nach einem SMS-Code fragen?", a: "Authentifizierungscodes sind extrem sensibel. Teile sie nicht mit jemandem, der sie per Anruf oder Nachricht verlangt; prüfe direkt bei der Bank." }, { q: "Soll ich antworten, um zu testen, ob es echt ist?", a: "Das ist nicht nötig. Sicherer ist die Prüfung über einen unabhängigen offiziellen Kanal." }] },
    identity: { signalsTitle: "Was du bei einem Profil prüfen solltest", stepsTitle: "So verifizierst du die Identität", signals: ["Kontoalter, Namensänderungen, Verlauf und zeitliche Konsistenz.", "Fotos, Biografie und Angaben, die sich außerhalb des Kontos prüfen lassen.", "Kontaktnetz, echte Interaktionen und unnatürliche Follower-Muster.", "Forderungen nach Geld, Investitionen, persönlichen Daten oder schnellem Wechsel auf einen anderen Kanal."], steps: ["Suche die Identität in anderen Quellen und vergleiche Fotos, Namen und Aktivität.", "Nutze eine angemessene Verifikation über einen anderen Kanal, wenn Risiko und Beziehung das rechtfertigen.", "Sende kein Geld und keine sensiblen Dokumente nur auf Grundlage des Profils."], faqs: [{ q: "Bedeuten wenige Beiträge, dass das Profil falsch ist?", a: "Nein. Das ist allein ein schwaches Signal; Gesamtkonsistenz, Verlauf und prüfbare Identität sind wichtiger." }, { q: "Beweist ein Videoanruf die Identität?", a: "Er liefert zusätzlichen Kontext, ist aber keine absolute Garantie. Die Prüfung sollte zum Risiko der geplanten Handlung passen." }, { q: "Was tun bei Identitätsdiebstahl?", a: "Sichere Beweise, informiere die echte Person über einen anderen Kanal und nutze die Meldefunktionen der Plattform." }] },
    investment: { signalsTitle: "Signale, die besondere Vorsicht erfordern", stepsTitle: "Was du vor einer Zahlung prüfen solltest", signals: ["Garantierte Renditen, unverhältnismäßige Gewinne oder keine nachvollziehbare Risikodarstellung.", "Druck, schnell einzuzahlen, Positionen zu erhöhen oder nicht auszuzahlen.", "Unternehmen, Lizenzen oder Fachleute lassen sich in unabhängigen Registern nicht bestätigen.", "Krypto-Zahlungen, Konten Dritter oder neue Gebühren zur Freigabe von Auszahlungen."], steps: ["Prüfe Unternehmen und regulatorischen Status bei der zuständigen offiziellen Quelle.", "Verstehe vor Einzahlung, wer das Geld verwahrt und wie Auszahlungen tatsächlich funktionieren.", "Sende kein weiteres Geld zur Rückholung einer Investition, bevor die Situation unabhängig geprüft wurde."], faqs: [{ q: "Beweist ein angezeigter Gewinnsaldo die Seriosität?", a: "Nein. Ein Bildschirmwert beweist weder, dass das Geld existiert, noch dass es ausgezahlt werden kann." }, { q: "Ist eine Gebühr zum Freischalten einer Auszahlung normal?", a: "Das kann ein starkes Risikosignal sein, besonders wenn bei jedem Auszahlungsversuch neue Gebühren auftauchen. Prüfe den Anbieter, bevor du mehr zahlst." }, { q: "Was, wenn ich bereits Geld oder Krypto gesendet habe?", a: "Sichere Adressen, Transaktions-Hashes, Belege und Gespräche und kontaktiere je nach Fall Anbieter, Bank oder zuständige Behörden möglichst schnell." }] },
    documents: { signalsTitle: "Punkte, die du finden solltest", stepsTitle: "So prüfst du vor Zustimmung oder Zahlung", signals: ["Identität der Parteien, Zweck des Dokuments und Angaben, die zur tatsächlichen Beziehung passen müssen.", "Beträge, Daten, Laufzeit, Verlängerungen, Sanktionen und Ausstiegsbedingungen.", "Bankkonten, Zahlungsdaten oder Änderungen gegenüber früheren Dokumenten.", "Unklare, widersprüchliche oder ungewöhnlich einseitige Klauseln."], steps: ["Vergleiche das Dokument mit Angebot, Gespräch oder früherer Vereinbarung, aus der es hervorgeht.", "Markiere alles, was du nicht prüfen kannst, und verlange eine schriftliche Erklärung.", "Bei erheblichen rechtlichen oder finanziellen Folgen sollte vor Unterschrift oder Zahlung professionell geprüft werden."], faqs: [{ q: "Kann Vonu sagen, ob eine Klausel rechtmäßig ist?", a: "Es ersetzt keine Rechtsberatung. Es kann helfen, Klauseln zu finden und zu ordnen, damit du weißt, was du prüfen oder fragen solltest." }, { q: "Bedeutet ein geändertes Bankkonto Betrug?", a: "Nicht immer, aber die Änderung sollte vor Zahlung über einen bekannten Kanal bestätigt werden." }, { q: "Welche Daten sollte ich vor der Analyse ausblenden?", a: "Teile keine Passwörter, Authentifizierungscodes, vollständigen Kartennummern oder unnötige hochsensible Daten." }] },
    manipulation: { signalsTitle: "Muster, auf die du achten solltest", stepsTitle: "So gewinnst du Entscheidungsspielraum zurück", signals: ["Wiederholter Druck, ohne genügend Zeit zu antworten, zu zahlen oder zu entscheiden.", "Schuldzuweisung, Drohungen, emotionaler Entzug oder Isolation von anderen Meinungen.", "Ständig wechselnde Darstellungen oder Leugnen leicht überprüfbarer Tatsachen.", "Wechsel von Belohnung und Druck, um ein bestimmtes Verhalten zu erreichen."], steps: ["Trenne überprüfbare Fakten von Interpretationen und bewahre den Gesamtkontext.", "Triff wichtige Entscheidungen nicht unter akutem Druck und sprich gegebenenfalls mit einer Vertrauensperson.", "Bei Drohung, Zwang oder persönlicher Gefahr haben professionelle oder offizielle Hilfen Vorrang."], faqs: [{ q: "Bedeutet ein heftiger Streit Manipulation?", a: "Nein. Kontext und Muster sind entscheidend; eine einzelne Interaktion reicht nicht für eine verlässliche Schlussfolgerung." }, { q: "Kann Vonu eine Person diagnostizieren?", a: "Nein. Vonu kann beobachtbares Verhalten ordnen, aber keine Persönlichkeit, psychische Gesundheit oder inneren Motive diagnostizieren." }, { q: "Welche Informationen helfen am meisten?", a: "Eine vollständige Folge von Nachrichten oder Ereignissen mit Daten und Kontext ist meist hilfreicher als ein einzelner Satz." }] },
    generic: { signalsTitle: "Die wichtigsten Signale", stepsTitle: "Eine einfache Prüfung vor dem Handeln", signals: ["Identität: Wer steckt wirklich dahinter und lässt sich das außerhalb des Kanals bestätigen?", "Konsistenz: Passen Domain, Verlauf, Angaben, Preise und Verhalten zusammen?", "Risiko der geforderten Handlung: Geld, Codes, Zugangsdaten, Dokumente oder sensible Informationen.", "Druck: Dringlichkeit, Drohungen oder Anreize, die unabhängige Prüfung verhindern sollen."], steps: ["Stoppe, wenn ein Fehler teuer wäre und wichtige Informationen fehlen.", "Prüfe mindestens eine unabhängige Quelle oder einen offiziellen Kanal.", "Analysiere URL, Nachricht oder Screenshot und entscheide erst mit geordneten Signalen."], faqs: [{ q: "Kann ein einziges Signal zeigen, ob etwas seriös ist?", a: "Meist nicht. Vertrauen steigt, wenn mehrere unabhängige Signale zusammenpassen und Unsicherheit ebenfalls berücksichtigt wird." }, { q: "Gibt Vonu ein endgültiges Urteil?", a: "Nein. Es zeigt Signale, verfügbare Belege und Unsicherheit, damit du den nächsten Prüfschritt wählen kannst." }, { q: "Was sollte ich zuerst prüfen?", a: "Identität und geforderte Handlung: Wer fragt, wie lässt sich die Person oder Organisation bestätigen und was würdest du verlieren, wenn die Anfrage falsch wäre?" }] },
  },
  ar: {
    web: { signalsTitle: "إشارات تستحق التحقق المتقاطع", stepsTitle: "ما الذي تفعله قبل الشراء أو الثقة", signals: ["هوية النشاط ووسائل الاتصال واتساق المعلومات القانونية.", "النطاق وعمره وإعادة التوجيه والتشابه مع علامات معروفة.", "الأسعار وطرق الدفع والإرجاع والضغط للتصرف بسرعة.", "السمعة في مصادر مستقلة واتساق ما يعد به الموقع مع ما يمكن التحقق منه خارجه."], steps: ["ابحث عن الشركة والنطاق بشكل مستقل ولا تعتمد فقط على روابط الموقع نفسه.", "عند الدفع، فضّل وسائل توفر حماية وتجنب التحويلات غير القابلة للعكس عند وجود شك.", "إذا وجدت تناقضًا، حلّل الرابط واحتفظ بلقطات شاشة قبل المتابعة."], faqs: [{ q: "هل HTTPS يعني أن الموقع آمن؟", a: "لا. HTTPS يشفّر الاتصال، لكن الموقع الاحتيالي قد يستخدم شهادة صالحة أيضًا." }, { q: "هل النطاق الجديد يثبت الاحتيال؟", a: "لا بمفرده. هو إشارة سياقية يجب جمعها مع الهوية والسمعة والمحتوى والسلوك التجاري." }, { q: "ماذا أفعل إذا دفعت بالفعل؟", a: "احتفظ بالأدلة وتواصل سريعًا مع البنك أو مزود الدفع واستخدم قنوات البلاغ أو الدعم الرسمية عند الحاجة." }] },
    link: { signalsTitle: "ما الذي تفحصه في الرابط", stepsTitle: "كيف تتحقق منه دون تعريض نفسك للخطر", signals: ["النطاق الحقيقي المسجل وليس النص الظاهر فقط.", "النطاقات الفرعية والحروف المتشابهة والروابط المختصرة والمعلمات التي تخفي الوجهة.", "سلاسل إعادة التوجيه وتغير النطاق قبل الصفحة النهائية.", "السياق: من أرسله، وما المطلوب، وهل يحاول خلق استعجال أو خوف."], steps: ["لا تدخل بيانات الدخول أو رموز المصادقة من رابط وصل إليك.", "افتح تطبيق أو موقع الجهة الرسمي بشكل منفصل وتحقق من التنبيه هناك.", "حلّل الرابط كنص قبل زيارته إذا بقي لديك شك."], faqs: [{ q: "هل أثق بالرابط إذا بدأ بـ https://؟", a: "لا. HTTPS يحمي الاتصال لكنه لا يضمن شرعية الوجهة." }, { q: "هل الروابط المختصرة خطيرة؟", a: "ليست خطيرة بالضرورة، لكنها تخفي الوجهة ولذلك تستحق حذرًا إضافيًا في الرسائل غير المتوقعة." }, { q: "ماذا لو فتحته بالفعل؟", a: "فتح الصفحة وحده لا يعني تلقائيًا اختراقًا. لا تدخل بيانات وأغلقها وغيّر بيانات الدخول إذا كنت قد أرسلتها." }] },
    capture: { signalsTitle: "ما الذي قد تكشفه لقطة الشاشة", stepsTitle: "كيف توفر سياقًا مفيدًا", signals: ["النطاق أو المرسل أو اسم المستخدم أو الهوية الظاهرة.", "طلبات المال أو الرموز أو بيانات الدخول أو المعلومات الشخصية.", "لغة الاستعجال أو التهديد أو المكافأة أو الضغط العاطفي.", "تناقضات بصرية وعناصر تقلّد جهة معروفة."], steps: ["حاول تضمين الجزء الذي يظهر المرسل أو الرابط أو السياق المحيط.", "أخفِ كلمات المرور وPIN وأرقام البطاقات الكاملة ورموز المصادقة.", "تحقق من أي استنتاج عبر القناة الرسمية للشخص أو الجهة المعنية."], faqs: [{ q: "هل تكفي لقطة الشاشة لإثبات الاحتيال؟", a: "لا. قد توفر إشارات مفيدة لكنها قد تكون ناقصة أو معدلة أو تفتقد سياقًا مهمًا." }, { q: "هل أرفع بيانات حساسة؟", a: "لا. أخفِ كلمات المرور والرموز وPIN وبيانات البطاقة الكاملة قبل التحليل." }, { q: "هل يستطيع Vonu اكتشاف صورة معدلة؟", a: "قد يشير إلى تناقضات مرئية لكنه لا يثبت أصالة الصورة جنائيًا أو فنيًا." }] },
    message: { signalsTitle: "إشارات شائعة في الرسائل الخطرة", stepsTitle: "ما الذي تفعله قبل الرد", signals: ["استعجال مصطنع: مهل قصيرة أو إيقاف أو غرامات أو تهديدات فورية.", "طلب رموز أو كلمات مرور أو بيانات بنكية أو تحويلات.", "روابط لا يتطابق نطاقها مع الجهة التي تدّعي إرسال الرسالة.", "مرسل أو رقم يبدو شرعيًا لكنه لا يمكن تأكيده من قناة مستقلة."], steps: ["لا ترد برموز المصادقة أو بيانات الدخول الحساسة.", "افتح التطبيق أو الموقع الرسمي يدويًا أو اتصل برقم رسمي تعرفه مسبقًا.", "احتفظ بالرسالة وحلّل النص أو الرابط أو لقطة الشاشة قبل اتخاذ القرار."], faqs: [{ q: "هل اسم المرسل يثبت هويته؟", a: "لا. يمكن تزوير أو تقليد الأسماء والعناوين الظاهرة في SMS والبريد والمكالمات." }, { q: "هل قد يطلب البنك رمز SMS؟", a: "رموز المصادقة شديدة الحساسية. لا تعطها لشخص يطلبها عبر اتصال أو رسالة؛ تحقق مباشرة مع البنك." }, { q: "هل أرد لأعرف إن كانت الرسالة حقيقية؟", a: "لا حاجة لذلك. التحقق عبر قناة رسمية مستقلة أكثر أمانًا." }] },
    identity: { signalsTitle: "ما الذي تفحصه في الحساب", stepsTitle: "كيف تتحقق من الهوية", signals: ["عمر الحساب وتغيّر الاسم والتاريخ واتساق التسلسل الزمني.", "الصور والسيرة والمعلومات التي يمكن التحقق منها خارج الحساب.", "شبكة العلاقات والتفاعلات الحقيقية وأنماط المتابعين غير الطبيعية.", "طلبات المال أو الاستثمار أو البيانات أو الانتقال السريع إلى قناة أخرى."], steps: ["ابحث عن الهوية في مصادر أخرى وقارن الصور والأسماء والنشاط.", "استخدم تحققًا مناسبًا عبر قناة مختلفة عندما يبرر مستوى الخطر ذلك.", "لا ترسل مالًا أو مستندات حساسة اعتمادًا على الحساب وحده."], faqs: [{ q: "هل قلة المنشورات تعني أن الحساب مزيف؟", a: "لا. هي إشارة ضعيفة بمفردها؛ الأهم هو الاتساق العام والتاريخ وإمكانية التحقق من الهوية." }, { q: "هل مكالمة الفيديو تثبت الهوية؟", a: "تضيف سياقًا لكنها ليست ضمانًا مطلقًا. يجب أن يتناسب مستوى التحقق مع خطورة الإجراء الذي ستقوم به." }, { q: "ماذا أفعل إذا كان هناك انتحال لشخص حقيقي؟", a: "احتفظ بالأدلة ونبّه الشخص الحقيقي عبر قناة أخرى واستخدم أدوات الإبلاغ في المنصة." }] },
    investment: { signalsTitle: "إشارات تتطلب حذرًا إضافيًا", stepsTitle: "ما الذي تتحقق منه قبل إرسال المال", signals: ["عوائد مضمونة أو أرباح مبالغ فيها أو غياب شرح حقيقي للمخاطر.", "ضغط للإيداع بسرعة أو زيادة الاستثمار أو عدم السحب.", "جهات أو تراخيص أو مختصون لا يمكن تأكيدهم في سجلات مستقلة.", "مدفوعات بالعملات المشفرة أو حسابات أطراف ثالثة أو رسوم جديدة لتحرير السحب."], steps: ["تحقق من الشركة والوضع التنظيمي في المصدر الرسمي المختص.", "افهم من يحتفظ بالأموال وكيف يعمل السحب فعليًا قبل الإيداع.", "لا ترسل أموالًا إضافية لاسترداد استثمار قبل التحقق المستقل من الوضع."], faqs: [{ q: "هل الرصيد الربحي الظاهر يثبت شرعية المنصة؟", a: "لا. الرصيد المعروض لا يثبت وجود المال أو إمكانية سحبه." }, { q: "هل دفع رسوم لفتح السحب أمر طبيعي؟", a: "قد يكون إشارة خطر مرتفعة، خصوصًا إذا ظهرت رسوم جديدة في كل محاولة سحب. تحقق من الجهة قبل دفع المزيد." }, { q: "ماذا لو أرسلت مالًا أو عملات مشفرة بالفعل؟", a: "احتفظ بالعناوين وهاش المعاملات والإيصالات والمحادثات وتواصل سريعًا مع المزود أو البنك أو الجهات المختصة حسب الحالة." }] },
    documents: { signalsTitle: "نقاط تستحق تحديدها", stepsTitle: "كيف تراجع قبل القبول أو الدفع", signals: ["هوية الأطراف وهدف المستند والبيانات التي يجب أن تتطابق مع العلاقة الحقيقية.", "المبالغ والتواريخ والمدة والتجديد والغرامات وشروط الخروج.", "الحسابات البنكية وبيانات الدفع أو التغييرات عن مستندات سابقة.", "بنود غامضة أو متناقضة أو منحازة بشكل غير معتاد لطرف واحد."], steps: ["قارن المستند بالعرض أو المحادثة أو الاتفاق السابق الذي نتج عنه.", "حدّد كل معلومة لا يمكنك التحقق منها واطلب توضيحًا مكتوبًا.", "إذا كانت النتيجة القانونية أو المالية كبيرة، استخدم مراجعة مختص قبل التوقيع أو الدفع."], faqs: [{ q: "هل يستطيع Vonu تحديد ما إذا كان البند قانونيًا؟", a: "لا يحل محل الاستشارة القانونية. يمكنه مساعدتك في تحديد البنود وتنظيمها لتعرف ما الذي يحتاج إلى مراجعة أو سؤال." }, { q: "هل تغير الحساب البنكي يعني احتيالًا؟", a: "ليس دائمًا، لكنه يجب أن يُؤكد عبر قناة معروفة قبل الدفع." }, { q: "ما البيانات التي يجب إخفاؤها قبل تحليل مستند؟", a: "تجنب مشاركة كلمات المرور ورموز المصادقة وأرقام البطاقات الكاملة والبيانات شديدة الحساسية غير الضرورية للمراجعة." }] },
    manipulation: { signalsTitle: "أنماط تستحق الملاحظة", stepsTitle: "كيف تستعيد مساحة لاتخاذ القرار", signals: ["ضغط متكرر للرد أو الدفع أو اتخاذ قرار دون وقت كافٍ.", "إشعار بالذنب أو تهديد أو عقاب عاطفي أو عزل عن آراء الآخرين.", "تغيير مستمر للرواية أو إنكار حقائق يسهل التحقق منها.", "التناوب بين المكافأة والضغط للحصول على سلوك محدد."], steps: ["افصل الحقائق القابلة للتحقق عن التفسيرات واحتفظ بالسياق الكامل.", "تجنب القرارات المهمة أثناء الضغط الفوري واستشر شخصًا موثوقًا عندما يكون ذلك مناسبًا.", "إذا وُجد تهديد أو إكراه أو خطر شخصي، أعط الأولوية للدعم المهني أو الرسمي."], faqs: [{ q: "هل الجدال القوي يعني وجود تلاعب؟", a: "لا. السياق والنمط مهمان؛ تفاعل واحد لا يكفي لاستنتاج موثوق." }, { q: "هل يستطيع Vonu تشخيص شخص؟", a: "لا. يستطيع Vonu تنظيم السلوكيات الملاحظة، وليس تشخيص الشخصية أو الصحة النفسية أو الدوافع الداخلية." }, { q: "ما المعلومات الأكثر فائدة؟", a: "تسلسل كامل للرسائل أو الأحداث مع التواريخ والسياق أكثر فائدة عادة من جملة منفردة." }] },
    generic: { signalsTitle: "الإشارات الأكثر أهمية", stepsTitle: "تحقق بسيط قبل التصرف", signals: ["الهوية: من يقف خلف الأمر فعلًا وهل يمكن تأكيده خارج القناة نفسها؟", "الاتساق: هل يتوافق النطاق والتاريخ والبيانات والأسعار والسلوك؟", "خطورة الإجراء المطلوب: مال أو رموز أو بيانات دخول أو مستندات أو معلومات حساسة.", "الضغط: استعجال أو تهديد أو حوافز لمنعك من التحقق بشكل مستقل."], steps: ["توقف إذا كانت تكلفة الخطأ مرتفعة والمعلومات ناقصة.", "تحقق عبر مصدر مستقل واحد على الأقل أو قناة رسمية.", "حلّل الرابط أو الرسالة أو لقطة الشاشة واتخذ القرار بعد ترتيب الإشارات."], faqs: [{ q: "هل تكفي إشارة واحدة لمعرفة ما إذا كان الأمر موثوقًا؟", a: "غالبًا لا. تزيد الثقة عندما تتفق عدة إشارات مستقلة مع أخذ عدم اليقين في الحسبان." }, { q: "هل يعطي Vonu حكمًا نهائيًا؟", a: "لا. يعرض الإشارات والأدلة المتاحة وعدم اليقين لمساعدتك على اختيار خطوة التحقق التالية." }, { q: "ما أول شيء يجب التحقق منه؟", a: "الهوية والإجراء المطلوب: من يطلب، وكيف تؤكد هويته، وما الذي قد تخسره إذا كان الطلب مزيفًا." }] },
  },
};

export const relatedIntentSlugs: Record<IntentSlug, IntentSlug[]> = {
  "comprobar-web-fiable": ["comprobar-tienda-online", "analizar-link-sospechoso", "es-fiable"],
  "comprobar-tienda-online": ["comprobar-web-fiable", "comprobar-factura", "analizar-link-sospechoso"],
  "analizar-link-sospechoso": ["comprobar-web-fiable", "analizar-sms-estafa", "email-sospechoso-estafa"],
  "analizar-captura-pantalla": ["analizar-sms-estafa", "detectar-perfil-falso", "es-fiable"],
  "analizar-sms-estafa": ["llamada-banco-codigo-sms", "analizar-link-sospechoso", "email-sospechoso-estafa"],
  "email-sospechoso-estafa": ["analizar-link-sospechoso", "analizar-sms-estafa", "comprobar-web-fiable"],
  "detectar-perfil-falso": ["analizar-captura-pantalla", "detectar-manipulacion", "es-fiable"],
  "comprobar-inversion-estafa": ["estafas-criptomonedas", "detectar-manipulacion", "es-fiable"],
  "revisar-contrato": ["revisar-contrato-alquiler", "revisar-contrato-servicios", "revisar-presupuesto"],
  "revisar-contrato-alquiler": ["revisar-contrato", "revisar-contrato-servicios", "comprobar-factura"],
  "comprobar-factura": ["revisar-presupuesto", "revisar-contrato", "comprobar-tienda-online"],
  "revisar-presupuesto": ["comprobar-factura", "revisar-contrato-servicios", "revisar-contrato"],
  "revisar-contrato-servicios": ["revisar-contrato", "revisar-presupuesto", "revisar-prestamo-financiacion"],
  "revisar-prestamo-financiacion": ["revisar-contrato", "revisar-contrato-servicios", "comprobar-factura"],
  "detectar-manipulacion": ["detectar-perfil-falso", "comprobar-inversion-estafa", "es-fiable"],
  "estafas-criptomonedas": ["comprobar-inversion-estafa", "detectar-manipulacion", "es-fiable"],
  "llamada-banco-codigo-sms": ["analizar-sms-estafa", "analizar-link-sospechoso", "email-sospechoso-estafa"],
  "es-fiable": ["comprobar-web-fiable", "analizar-sms-estafa", "detectar-perfil-falso"],
};

export function isIntentSlug(slug: IndexedPublicSlug): slug is IntentSlug {
  return (INTENT_SLUGS as readonly string[]).includes(slug);
}

export function getIntentContent(locale: SupportedLocale, slug: IntentSlug) {
  const group = groupBySlug[slug];
  return {
    answer: answers[locale][slug],
    ...groupCopy[locale][group],
    related: relatedIntentSlugs[slug],
  };
}
